name: Deploy to Firebase Hosting

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Firebase Deployment workflow
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Build project
        run: npm run build
      - name: Deploy to Firebase Hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-key.json
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JYOSHIMANOHAR_COM }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > gcp-key.json
          npx firebase-tools deploy --only hosting --project jyoshimanohar-com --non-interactive --force
